### ISSUE TITLE
Hide weather feature

### ISSUE THREAD

**Issue by FTno** [dasbiswajit/worldclockwidget#17]
Thanks, it's nice to have an open source world clock app.

As I'm mostly interested in times for some places around the world and not the weather conditions (thus no need to go through the hassle of making accounts for getting a key), I would like to propose an option to hide the weather part as it takes up a lot of space in the UI (as seen in the screenshot below).

![worlclock](https://user-images.githubusercontent.com/16176811/74020044-028f6f80-4999-11ea-9947-f992b8bb096f.png)

**Comment by dasbiswajit** [comment]
@FTno Thanks for reaching us.

1. For showing city name and time there is a specific widget available with the app. you can use that. you do not have to open the APP 👍  
2. Please have a look at the Youtube Video [for adding widget](https://youtu.be/sEQ0FUwqTN4?t=74).
3. Please use the playsrote [version](https://play.google.com/store/apps/details?id=ch.corten.aha.worldclock) for the latest features.

**Comment by FTno** [comment]
Thanks for answer.
