### ISSUE TITLE
Official take over?

### ISSUE THREAD

**Issue by ildar** [dasbiswajit/worldclockwidget#6]
Hi! Nice to see the code is alive and developed.
Yet one important question remain: is this the official take over the project? I mean there's the difference if you just fork:
Will you use the app id / name? Do you have Armin's permission for that?

**Comment by dasbiswajit** [comment]
@ildar yes. I have taken maintainence of the repo long back. Yes the app id will be the same as it is running under my account . Thanks for your support.

**Comment by ildar** [comment]
I see.
Then when a new release ready, we need to make proper changes in F-Droid. I
can help with it if needed.

Meanwhile is it worth to file here my issues:
https://github.com/arminha/worldclockwidget/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aildar
marked as "wontfix" ?

**Comment by dasbiswajit** [comment]
@ildar Thanks for your support. I will focus on F-droid version. Besides my time.

1.  F-droid repo is still pointing to the old [project](https://github.com/arminha/worldclockwidget). Need to work on that. 
2. @arminha do you like to update the new repository address in the old [repo](https://github.com/arminha/worldclockwidget). I have sent you an invite in this.

3. @ildar do you mind to create 2 separate issue here. If you are working then a PR will be good start. We can start it from there.

**Comment by ildar** [comment]
1. F-Droid metadata can be easily fixed, no need to bother @arminha
2. It's actually no hurry until a new release ready. The 1.9.0 is already
in F-Droid BTW.

**Comment by dasbiswajit** [comment]
@ildar sure. Are you creating a separate issue tracker for that

**Comment by ildar** [comment]
2. It's actually no hurry until a new release ready.

**Comment by dasbiswajit** [comment]
sure. Closing this as of now
